version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "recipe-services"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tprk14chilqk"
s3_prefix = "recipe-services"
region = "us-west-2"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
